### ISSUE TITLE
Confusing statement.

### ISSUE THREAD

**Issue by hojjatabdollahi** [ralfbiedert/cheats.rs#103]
In the "Strength" section of the "Hello Rust" it says:

> can avoid 70% of all (memory-related) safety issues present in C / C++

This sounds like Rust can avoid 70% of memory-related issues, and can not handle 30% of memory-related issues. 
Maybe it should be reworded. Here is a suggestion (I'm not a native speaker): "can avoid memory-related safety issues (memory-related issues are 70% of all safety issues)"

**Comment by ralfbiedert** [comment]
Hi, thanks for the suggestion!

> can avoid memory-related safety issues (memory-related issues are 70% of all safety issues)"

I'd like to keep things in parentheses rather short, how about:

> can avoid 70% of all safety issues present in C / C++, and most memory issues.

**Comment by hojjatabdollahi** [comment]
> can avoid 70% of all safety issues present in C / C++, and most memory issues.

The "and" make it feel like you are saying in addition to the 70% it also avoids most memory issues as well. 
Maybe this:
> can avoid 70% of all safety issues present in C / C++, mostly memory issues.
However, saying that those issues are "present in C / C++" is not correct either. 

- Rust can avoid memory safety issues.
- Roughly 70% of the security issues that the MSRC assigns a CVE to are memory safety issues.

Maybe, something like this:
> can avoid memory safety issues. Note: 70% of CVE assigned issues are memory-related

**Comment by ralfbiedert** [comment]
> The "and" make it feel like you are saying in addition to the 70% it also avoids most memory issues as well.

Yes, this is what I want to say there. Do you disagree?

- It can avoid 70% of all security issues as indicated by that link (the memory related CVEs)
- And, via the same reasoning, we can also say it avoids most other memory issues (e.g., regular memory segfaults, UB, that did not result in an CVE)

**Comment by hojjatabdollahi** [comment]
> Yes, this is what I want to say there. Do you disagree?
I think it should be clear that 70% refers to "all memory safety" issues. If you say 
> can avoid 70% of all safety issues present in C / C++, and most memory issues.
It feels like: Rust can avoid 70% of all safety issues (memory or not), and by the way, it also can avoid most memory issues as well. 

> Why would this not be correct?
Yes, you are right. The issues were in C / C++. However, they were in Microsoft's codes. It does not inherently exist in C / C++. For example, if you check the vulnerabilities reported in the Linux Kernel the percentage could go from 70% to 90% or 40%.  

My point is saying "Rust can avoid 70% of all safety issues present in C / C++" is not accurate. I am not sure what the correct wording is, but it should say: "Rust can avoid memory safety issues. Memory safety vulnerabilities constitute around %70 of all C / C++ CVEs recorded by MSRC~\cite{}. 
I understand expressing this as a bullet point is hard. But just thought I would suggest a clarification.

**Comment by ralfbiedert** [comment]
Sorry for the delay. 

> I think it should be clear that 70% refers to "all memory safety" issues. [...] It feels like: Rust can avoid 70% of all safety issues (memory or not), and by the way, it also can avoid most memory issues as well.

This is again exactly what I am trying to say, two parts:

- Rust can avoid most memory issues present in C / C++ (out-of-bounds, UB, segfaults, ... pretty much all except leaks), regardless of whether they are security related or not. I think this one is not really disputed. 

- Because of the previous point, Rust therefore also avoids 70% of **all** safety issues present in C / C++ code bases, as the fraction of memory safety issues relative to all safety issues is 70%. That numbers comes from the report linked, quoting the relevant parts (emphasis mine):

> As we’ve seen, roughly **70% of the security issues that the MSRC assigns a CVE to are memory safety issues**. This means that if that software had been written in Rust, **70% of these security issues would most likely have been eliminated**.

Similar numbers have been reported by other teams. 

> However, they were in Microsoft's codes. It does not inherently exist in C / C++. For example, if you check the vulnerabilities reported in the Linux Kernel the percentage could go from 70% to 90% or 40%.

Yes, I agree some code bases could have higher or lower numbers. However, two sources have independently arrived at a 70% ballpark number from different code bases. Unless more or better data is available, I think that number is fair game for a general "grand average" statement about the prevalence of issues in C within the scope of this cheat sheet.


> My point is saying "Rust can avoid 70% of all safety issues present in C / C++" is not accurate. 

Again, in light of the articles _"70% of the security issues that the MSRC assigns a CVE to are memory safety issues"_ I think it is an accurate statement (unless you argue CVEs and overall safety issues are not the same thing, which I would counter by saying for the scope of this site they are).

With that said I changed the statement to the one discussed above and hope it got a bit clearer. Given the discussion so far I'll also close this issue for now, but I'm happy to revisit if substantially new arguments are made.
