### ISSUE TITLE
Asking about a resource about programming language specification

### ISSUE THREAD

**Issue by andraantariksa** [ralfbiedert/cheats.rs#121]
> no formal language specification, can prevent legal use in some domains (aviation, medical, …).

Can you give me the further resource about it?

**Comment by ralfbiedert** [comment]
Disclaimer, I haven't worked with certified software, so I only have 2nd hand knowledge.

Some pointers:

- [SO question regarding programming languages](https://aviation.stackexchange.com/questions/3608/what-programming-languages-are-used-for-equipment-onboard-aircraft?noredirect=1&lq=1)  in aviation, and [another one about operating systems](https://softwareengineering.stackexchange.com/questions/153266/what-operating-systems-are-used-in-airplanes-and-what-programming-languages-are)
- [SO question about compiler qualification](https://stackoverflow.com/questions/49516502/how-to-certify-a-compiler-for-functional-safety)
- Wikipedia on [DO-178B](https://en.wikipedia.org/wiki/DO-178B), [DO-178C](https://en.wikipedia.org/wiki/DO-178C) and [avionics software](https://en.wikipedia.org/wiki/Avionics_software)



Basic narrative is:
- Avionics & co have stringent design and traceability requirements
- A certified compiler dramatically helps mapping those requirements to verified machine output
- The agreements that come with purchasing a certified compiler also help mitigate legal risk (if your plane ever crashes and it turns out it was a compiler bug the "but the people on the internet said it would work"-defense might not fly; pun mildly intended)

I'm closing this issue since it's not actionable, but feel free to post follow-up.
