### ISSUE TITLE
Slice ranges (like `[..b]`) described as "without starting point" potentially missleading

### ISSUE THREAD

**Issue by hoijui** [ralfbiedert/cheats.rs#147]
I have seen it elsewhere, an I know what it means, but if I had no clue, I might be confused by this.
I could think:

* how do I define the starting point then.. later on?
* does this mean it starts at index `1`, as `0` is the starting point, and it is without that?

Would it be correct and ok for you, to replace "without starting point" with "starting at index `0`", or "with implicit starting index `0`"?

**Comment by ralfbiedert** [comment]
I agree the wording could be improved, but unfortunately it's not that simple:

>Slice ranges [...] Would it be correct and ok for you, to replace "without starting point" with "starting at index 0", or "with implicit starting index 0"?

The `[..b]` construct and friends are not _slice_ ranges, they are just _ranges_. They happen to be used a lot with slices (which is why on the site they're close together), but they are separate concepts.

- The slice type `[T]` points to some memory and length and, as you say, usually has a first element one would in a human-to-human conversation call `0`.
- To access that element in Rust you'd write `x[0]`, or to create a sub-slice containing it you'd do for example `x[0..10]`
- What 'sort of' happens is the compiler creates a usize `0`, or a `Range { start: 0, end: 10}` and then respectively invokes* `Index<usize> for [T]` or `Index<Range<usize>> for [T]`. These implementations then **happen** to give you the first element, or a slice containing the first 10 elements as you'd expect, since "it was the intuitive thing to do". (*ok, for slices its more complicated, but imagine using some custom collection).
- Now, using `..10` things get more interesting. That construct becomes  `RangeTo`. However, `RangeTo` by itself does _not_ consider `0` its starting point:

    ```rust
    let my_range = ..3;
    dbg!(my_range.contains(&-10));
    ```
    Prints `my_range.contains(&-10) = true`! Still, `[T]` does implement `Index<RangeTo<usize>>` and it does what you'd expect in this case. 
- That said, it would be easy to imagine a collection `ℤ` of mathematical integers where `Index<RangeTo<usize>>` should not start at `0` (although practically it would be a bit ugly to implement given `Index` forces a `&R` on return).
