### ISSUE TITLE
`fn f() where Self: R {} Other R useful w. dflt. fn. (non dflt. would need be impl'ed anyway).`

### ISSUE THREAD

**Issue by xxshady** [ralfbiedert/cheats.rs#187]
![изображение](https://github.com/ralfbiedert/cheats.rs/assets/54737754/68c9d17c-11ee-4964-992f-42eb09da1f3b)

What does it mean?

**Comment by ralfbiedert** [comment]
Apologies, I'm not really happy about that line as it's too condensed. The literal expansion is 

> Other R bounds can be useful with default functions (`fn`). (Non default ones would need be implemented anyway).

What it means is, the act of applying an `where Self: R` bound to a function can be useful in cases where you want that function to be only available if the type in question _also_ implements an optional `R`.

The `R` is optional in this case because if you wanted it mandatory you'd already have made it  mandatory in your trait declaration like so `trait T: R`.

The part about "Non default ones would need be implemented anyway" means that adding a `where Self: R` is useless in non-default functions: If you had a `fn f() where Self: R;` and left it to the implementing third party, that party would have a problem. It _must_ implement `f` as it's a trait requirement, but it could only do so if the type in question "accidentally" also implemented `R` (as it was not mandatory to start with)

**Comment by xxshady** [comment]
Thanks for the explanation
