### ISSUE TITLE
suggestion: note about Cargo.lock and git

### ISSUE THREAD

**Issue by yaahc** [ralfbiedert/cheats.rs#60]
I'm not sure if this is worthy of inclusion but I've had multiple times where I forgot and had to look up if I should or shouldn't commit Cargo.lock for bins and libs.

It might be worth adding a note somewhere that mentions that Cargo.lock should be version controlled for bins and not for libs so that people can easily find the rule when they forget it. `cargo new --lib` adds it to the .gitignore file by default, so this may be an issue most people don't worry about, I'll leave it up to you to determine if it should be included.

**Comment by ralfbiedert** [comment]
Hm, I'm not sure where to add this. It's too little for it's own section, but it doesn't seem to fit anywhere else. 

A thought that crossed my mind was adding a "Project Anatomy" section explaining what goes where, but I'm not sure if that isn't already solved for most people by just using the standard tools.

**Comment by kud1ing** [comment]
I think this is worthy. Maybe in https://cheats.rs/#tooling which is about `cargo`.

**Comment by ralfbiedert** [comment]
> Maybe in https://cheats.rs/#tooling which is about cargo?

Tooling so far is about using existing tools. I think it would look a bit out-of-place just talking about these two files there.

Generally, adding them just for the sake of avoiding Git mistakes sets the bar too low IMO (it's not a mental blocker, in most cases it has no consequences and it can easily be fixed), which is why I would prefer mixing that information into a bigger section; however one that is a about files / project layout or something similar. 

Then, however, comes the question, is _that_ section actually needed / wanted?

**Comment by ralfbiedert** [comment]
Note to self: 

If there is a (project) anatomy section, maybe it should also have absolute MVP examples how a benchmark and unit test have to look like. 

After all these years, I still don't manage to write a benchmark from scratch w/o having to look up how I did it the previous time ...

**Comment by ralfbiedert** [comment]
Project anatomy section created. Feel free to reopen / comment.

**Comment by yaahc** [comment]
You're the freaking best. Ty for doing this!

**Comment by kud1ing** [comment]
Nice. What would you think about linking Cargo in this section to https://cheats.rs/#tooling instead of https://doc.rust-lang.org/cargo/index.html ? This way, people could stay in cheat sheet land longer.

**Comment by ralfbiedert** [comment]
Good idea, thanks.
