### ISSUE TITLE
Suggestion: Section about "Features of Last Resort"

### ISSUE THREAD

**Issue by kud1ing** [ralfbiedert/cheats.rs#85]
https://users.rust-lang.org/t/does-rust-have-a-feature-of-last-resort/34891

* `clone()`
...

**Comment by ralfbiedert** [comment]
It definitely sounds cool, but I'm worried it's somewhat arbitrary:

- `TypeId` 
- `unsafe`
- Lifetimes out of thin air
- HRTBs 
- `transmute`
- FFI + Linking with C
- Turbofish 
- ...

Would that be a section with just that?  Should these items just diffuse into the rest of the sheet?

**Comment by kud1ing** [comment]
I think it supports the "how do i quickly ...?" spirit in general.
How that would fit in here exactly, i don't know yet.

**Comment by ralfbiedert** [comment]
I think the trouble I have creating a dedicated section is: 

In the cases you have to resort to them you probably "should really know" what you are doing (unsafe, lifetimes out of thin air, transmute, FFI). I don't mind listing them in such a context in general, but I don't think we have the space to explain each to be useful in a "last resort" context. 

Without such context however, just listing them under the umbrella "if nothing else works try ... a transmute" for people who don't know about these concepts already is not a message we should send.

That said, we have a section on `unsafe` now, I'd like to expand HRTBs more, and I could even (in general) imagine some FFI guides at a later point. 

I'm closing this because I'm starting believe the section is not what we should have. If new arguments are made I'm willing to reconsider though.
